import { todayISO } from '../../lib/format'

/**
 * Lets the clinic owner confirm branding looks right before finishing setup —
 * mirrors the real letterhead layout used on generated invoice/prescription PDFs.
 */
export default function InvoicePreview({ clinic }) {
  return (
    <div className="lg:sticky lg:top-4">
      <p className="text-xs font-semibold uppercase tracking-wide text-black/35 mb-2">Live Preview — this is how your invoice will look</p>
      <div className="rounded-2xl border border-black/10 bg-white p-5 shadow-sm text-[13px]">
        <div className="flex items-start gap-3 pb-3 border-b-2 border-[var(--color-primary)]">
          {clinic.logoDataUrl ? (
            <img src={clinic.logoDataUrl} alt="" className="w-12 h-12 rounded-lg object-cover shrink-0" />
          ) : (
            <div className="w-12 h-12 rounded-lg bg-[var(--color-secondary)] shrink-0" />
          )}
          <div className="min-w-0 flex-1">
            <p className="font-bold text-[var(--color-primary)] font-[family-name:var(--font-heading)] truncate">
              {clinic.clinic_name || 'Your Clinic Name'}
            </p>
            {clinic.tagline ? <p className="text-[11px] text-black/40 italic truncate">{clinic.tagline}</p> : null}
            <p className="text-[11px] text-black/50 truncate">
              {clinic.doctors?.filter((d) => d.name).map((d) => d.name).join(' · ') || 'Dr. Your Name, MBBS'}
            </p>
          </div>
          <div className="text-right text-[10px] text-black/40 shrink-0">
            <p className="truncate max-w-[120px]">{clinic.address || 'Clinic address'}</p>
            <p>{clinic.phone || '03xx-xxxxxxx'}</p>
          </div>
        </div>

        <div className="flex items-center justify-between mt-3 mb-2">
          <p className="font-bold font-[family-name:var(--font-heading)] text-[var(--color-text)]">INVOICE</p>
          <p className="text-[11px] text-black/40">INV-{new Date().getFullYear()}-00001 · {todayISO()}</p>
        </div>

        <div className="rounded-lg bg-[var(--color-secondary)]/60 px-3 py-2 mb-2">
          <p className="text-[11px] text-black/40">Billed To</p>
          <p className="font-semibold">Sample Patient (SHF-00001)</p>
        </div>

        <table className="w-full text-[11px]">
          <thead>
            <tr className="text-left text-[var(--color-primary)] border-b border-black/10">
              <th className="py-1.5 font-semibold">Description</th>
              <th className="py-1.5 font-semibold text-right">Qty</th>
              <th className="py-1.5 font-semibold text-right">Amount</th>
            </tr>
          </thead>
          <tbody className="text-black/60">
            <tr className="border-b border-black/5"><td className="py-1.5">Consultation Fee</td><td className="text-right">1</td><td className="text-right">Rs. 1,500</td></tr>
            <tr><td className="py-1.5">Dressing & Medicine</td><td className="text-right">1</td><td className="text-right">Rs. 800</td></tr>
          </tbody>
        </table>

        <div className="flex justify-end mt-2">
          <div className="text-right text-[12px]">
            <p className="font-bold text-[var(--color-text)]">Total: Rs. 2,300</p>
          </div>
        </div>

        <p className="text-center text-[10px] text-black/30 mt-4 pt-2 border-t border-black/5">
          Generated by Shifa Suite — Ilaaj aap karein, baqi hum sambhalte hain
        </p>
      </div>
    </div>
  )
}
