const path = require('node:path')
const fs = require('node:fs')
const { app } = require('electron')
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib')

const TEAL = rgb(0x0e / 255, 0x7c / 255, 0x86 / 255)
const CHARCOAL = rgb(0x33 / 255, 0x33 / 255, 0x33 / 255)
const CORAL = rgb(0xf2 / 255, 0x99 / 255, 0x4a / 255)
const GREY = rgb(0.45, 0.45, 0.45)
const PAGE_W = 595.28 // A4
const PAGE_H = 841.89
const MARGIN = 48

function exportsDir(sub) {
  const dir = path.join(app.getPath('userData'), 'exports', sub)
  fs.mkdirSync(dir, { recursive: true })
  return dir
}

async function loadLogoImage(pdfDoc, logoPath) {
  if (!logoPath || !fs.existsSync(logoPath)) return null
  try {
    const bytes = fs.readFileSync(logoPath)
    const ext = path.extname(logoPath).toLowerCase()
    if (ext === '.png') return await pdfDoc.embedPng(bytes)
    if (ext === '.jpg' || ext === '.jpeg') return await pdfDoc.embedJpg(bytes)
  } catch {
    return null
  }
  return null
}

function safeJson(str, fallback) {
  if (!str) return fallback
  try {
    return JSON.parse(str)
  } catch {
    return fallback
  }
}

async function drawLetterhead(pdfDoc, page, fonts, clinic) {
  let cursorY = PAGE_H - MARGIN
  const logo = await loadLogoImage(pdfDoc, clinic?.logo_path)

  if (logo) {
    const logoH = 48
    const logoW = (logo.width / logo.height) * logoH
    page.drawImage(logo, { x: MARGIN, y: cursorY - logoH, width: logoW, height: logoH })
  }

  const textX = logo ? MARGIN + 64 : MARGIN
  page.drawText(clinic?.clinic_name || 'Clinic Name', {
    x: textX,
    y: cursorY - 16,
    size: 18,
    font: fonts.bold,
    color: TEAL,
  })
  if (clinic?.tagline) {
    page.drawText(clinic.tagline, { x: textX, y: cursorY - 32, size: 9, font: fonts.italic || fonts.regular, color: GREY })
  }

  const doctors = safeJson(clinic?.doctors, [])
  const doctorLine = doctors.map((d) => `${d.name}${d.qualification ? ' · ' + d.qualification : ''}`).join('   |   ')
  if (doctorLine) {
    page.drawText(doctorLine, { x: textX, y: cursorY - 46, size: 9, font: fonts.regular, color: CHARCOAL })
  }

  // right-aligned contact block
  const contactLines = [
    clinic?.address,
    [clinic?.phone, clinic?.whatsapp ? `WhatsApp: ${clinic.whatsapp}` : null].filter(Boolean).join('   '),
    clinic?.email,
  ].filter(Boolean)
  contactLines.forEach((line, i) => {
    const w = fonts.regular.widthOfTextAtSize(line, 8.5)
    page.drawText(line, { x: PAGE_W - MARGIN - w, y: cursorY - 14 - i * 11, size: 8.5, font: fonts.regular, color: GREY })
  })

  cursorY -= 64
  page.drawLine({ start: { x: MARGIN, y: cursorY }, end: { x: PAGE_W - MARGIN, y: cursorY }, thickness: 1.5, color: TEAL })
  return cursorY - 24
}

function drawFooter(page, fonts, clinic) {
  const y = MARGIN - 12
  page.drawLine({ start: { x: MARGIN, y: y + 18 }, end: { x: PAGE_W - MARGIN, y: y + 18 }, thickness: 0.75, color: rgb(0.85, 0.85, 0.85) })
  const leftParts = ['Generated by Shifa Suite']
  if (clinic?.registration_no) leftParts.push(`Reg. No: ${clinic.registration_no}`)
  page.drawText(leftParts.join('  ·  '), { x: MARGIN, y, size: 7.5, font: fonts.italic || fonts.regular, color: GREY })
  const support = 'Support: wa.me/923109888092'
  const w = fonts.regular.widthOfTextAtSize(support, 7.5)
  page.drawText(support, { x: PAGE_W - MARGIN - w, y, size: 7.5, font: fonts.regular, color: GREY })
}

async function buildBaseDoc() {
  const pdfDoc = await PDFDocument.create()
  const fonts = {
    regular: await pdfDoc.embedFont(StandardFonts.Helvetica),
    bold: await pdfDoc.embedFont(StandardFonts.HelveticaBold),
    italic: await pdfDoc.embedFont(StandardFonts.HelveticaOblique),
  }
  return { pdfDoc, fonts }
}

function fmtMoney(n) {
  const num = Number(n || 0)
  return `Rs. ${num.toLocaleString('en-PK', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`
}

// ───────────────────────────── Invoice ─────────────────────────────

async function generateInvoicePdf(db, invoiceId) {
  const invoice = db.prepare('SELECT * FROM invoices WHERE id = ?').get(invoiceId)
  if (!invoice) throw new Error('Invoice not found')
  const patient = db.prepare('SELECT * FROM patients WHERE id = ?').get(invoice.patient_id)
  const items = db.prepare('SELECT * FROM invoice_items WHERE invoice_id = ?').all(invoiceId)
  const payments = db.prepare('SELECT * FROM payments WHERE invoice_id = ? ORDER BY paid_at ASC').all(invoiceId)
  const clinic = db.prepare('SELECT * FROM clinic_profile WHERE id = 1').get()

  const { pdfDoc, fonts } = await buildBaseDoc()
  const page = pdfDoc.addPage([PAGE_W, PAGE_H])
  let y = await drawLetterhead(pdfDoc, page, fonts, clinic)

  page.drawText('INVOICE', { x: MARGIN, y, size: 16, font: fonts.bold, color: CHARCOAL })
  const metaLines = [
    `Invoice No: ${invoice.invoice_no}`,
    `Date: ${invoice.invoice_date}`,
    `Status: ${invoice.status.toUpperCase()}`,
  ]
  metaLines.forEach((line, i) => {
    const w = fonts.regular.widthOfTextAtSize(line, 9.5)
    page.drawText(line, { x: PAGE_W - MARGIN - w, y: y + 4 - i * 13, size: 9.5, font: fonts.regular, color: CHARCOAL })
  })
  y -= 28

  page.drawText('Billed To', { x: MARGIN, y, size: 9, font: fonts.bold, color: TEAL })
  y -= 14
  page.drawText(`${patient?.full_name || 'Walk-in Patient'}  (${patient?.patient_code || '-'})`, {
    x: MARGIN, y, size: 10.5, font: fonts.bold, color: CHARCOAL,
  })
  y -= 13
  if (patient?.phone) {
    page.drawText(`Phone: ${patient.phone}`, { x: MARGIN, y, size: 9, font: fonts.regular, color: GREY })
    y -= 13
  }
  y -= 12

  // table header
  const cols = [
    { key: 'description', label: 'Description', x: MARGIN, w: 260 },
    { key: 'quantity', label: 'Qty', x: MARGIN + 270, w: 50 },
    { key: 'unit_price', label: 'Unit Price', x: MARGIN + 330, w: 90 },
    { key: 'total', label: 'Amount', x: MARGIN + 430, w: 90 },
  ]
  page.drawRectangle({ x: MARGIN, y: y - 6, width: PAGE_W - MARGIN * 2, height: 22, color: rgb(0.91, 0.96, 0.96) })
  cols.forEach((c) => page.drawText(c.label, { x: c.x + 4, y: y, size: 9, font: fonts.bold, color: TEAL }))
  y -= 26

  items.forEach((item) => {
    if (y < 140) {
      drawFooter(page, fonts, clinic)
      const newPage = pdfDoc.addPage([PAGE_W, PAGE_H])
      y = PAGE_H - MARGIN
      return drawRow(newPage, item) // note: simplified — long invoices are uncommon for clinics
    }
    drawRow(page, item)
  })

  function drawRow(targetPage, item) {
    targetPage.drawText(String(item.description).slice(0, 60), { x: cols[0].x + 4, y, size: 9.5, font: fonts.regular, color: CHARCOAL })
    targetPage.drawText(String(item.quantity), { x: cols[1].x + 4, y, size: 9.5, font: fonts.regular, color: CHARCOAL })
    targetPage.drawText(fmtMoney(item.unit_price), { x: cols[2].x + 4, y, size: 9.5, font: fonts.regular, color: CHARCOAL })
    targetPage.drawText(fmtMoney(item.total), { x: cols[3].x + 4, y, size: 9.5, font: fonts.regular, color: CHARCOAL })
    y -= 20
  }

  y -= 6
  page.drawLine({ start: { x: MARGIN + 270, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.75, color: rgb(0.85, 0.85, 0.85) })
  y -= 18

  const totals = [
    ['Subtotal', invoice.subtotal],
    ['Discount', -invoice.discount],
    ['Tax', invoice.tax],
    ['Total', invoice.total],
    ['Paid', invoice.paid_amount],
    ['Balance Due', invoice.due_amount],
  ]
  totals.forEach(([label, val], i) => {
    const isTotal = label === 'Total' || label === 'Balance Due'
    const font = isTotal ? fonts.bold : fonts.regular
    const color = label === 'Balance Due' && val > 0 ? rgb(0.92, 0.34, 0.34) : CHARCOAL
    page.drawText(label, { x: MARGIN + 330, y: y - i * 16, size: 9.5, font, color })
    const valStr = fmtMoney(val)
    const w = font.widthOfTextAtSize(valStr, 9.5)
    page.drawText(valStr, { x: PAGE_W - MARGIN - w, y: y - i * 16, size: 9.5, font, color })
  })
  y -= totals.length * 16 + 20

  if (payments.length) {
    page.drawText('Payment History', { x: MARGIN, y, size: 9, font: fonts.bold, color: TEAL })
    y -= 14
    payments.forEach((p) => {
      page.drawText(`${p.paid_at.slice(0, 16)}   ${p.mode.toUpperCase()}   ${fmtMoney(p.amount)}${p.reference ? '   Ref: ' + p.reference : ''}`, {
        x: MARGIN, y, size: 8.5, font: fonts.regular, color: GREY,
      })
      y -= 12
    })
  }

  if (invoice.notes) {
    y -= 10
    page.drawText('Notes:', { x: MARGIN, y, size: 9, font: fonts.bold, color: TEAL })
    y -= 13
    page.drawText(invoice.notes.slice(0, 120), { x: MARGIN, y, size: 9, font: fonts.regular, color: CHARCOAL })
  }

  drawFooter(page, fonts, clinic)

  const bytes = await pdfDoc.save()
  const dir = exportsDir('invoices')
  const filePath = path.join(dir, `${invoice.invoice_no}.pdf`)
  fs.writeFileSync(filePath, bytes)
  return filePath
}

// ───────────────────────────── Prescription ─────────────────────────────

async function generatePrescriptionPdf(db, prescriptionId) {
  const presc = db.prepare('SELECT * FROM prescriptions WHERE id = ?').get(prescriptionId)
  if (!presc) throw new Error('Prescription not found')
  const patient = db.prepare('SELECT * FROM patients WHERE id = ?').get(presc.patient_id)
  const doctor = presc.doctor_id ? db.prepare('SELECT * FROM users WHERE id = ?').get(presc.doctor_id) : null
  const items = db
    .prepare('SELECT * FROM prescription_items WHERE prescription_id = ? ORDER BY sort_order ASC, id ASC')
    .all(prescriptionId)
  const clinic = db.prepare('SELECT * FROM clinic_profile WHERE id = 1').get()

  const { pdfDoc, fonts } = await buildBaseDoc()
  const page = pdfDoc.addPage([PAGE_W, PAGE_H])
  let y = await drawLetterhead(pdfDoc, page, fonts, clinic)

  page.drawText('PRESCRIPTION', { x: MARGIN, y, size: 16, font: fonts.bold, color: CHARCOAL })
  const metaLines = [`Rx No: ${presc.prescription_no}`, `Date: ${presc.presc_date}`]
  if (doctor) metaLines.push(`Dr. ${doctor.full_name}${doctor.qualification ? ' (' + doctor.qualification + ')' : ''}`)
  metaLines.forEach((line, i) => {
    const w = fonts.regular.widthOfTextAtSize(line, 9.5)
    page.drawText(line, { x: PAGE_W - MARGIN - w, y: y + 4 - i * 13, size: 9.5, font: fonts.regular, color: CHARCOAL })
  })
  y -= 30

  page.drawText(`Patient: ${patient?.full_name || '-'}   (${patient?.patient_code || '-'})`, {
    x: MARGIN, y, size: 10.5, font: fonts.bold, color: CHARCOAL,
  })
  y -= 13
  const subLine = [
    patient?.gender, patient?.dob ? `DOB: ${patient.dob}` : null, patient?.phone ? `Ph: ${patient.phone}` : null,
  ].filter(Boolean).join('   |   ')
  if (subLine) {
    page.drawText(subLine, { x: MARGIN, y, size: 9, font: fonts.regular, color: GREY })
    y -= 13
  }
  y -= 8

  if (presc.diagnosis) {
    page.drawText('Diagnosis:', { x: MARGIN, y, size: 9, font: fonts.bold, color: TEAL })
    page.drawText(presc.diagnosis.slice(0, 90), { x: MARGIN + 64, y, size: 9, font: fonts.regular, color: CHARCOAL })
    y -= 18
  }

  // Rx symbol + drug list
  page.drawText('℞', { x: MARGIN, y, size: 22, font: fonts.bold, color: CORAL })
  y -= 28

  items.forEach((item, idx) => {
    page.drawText(`${idx + 1}.  ${item.drug_name}`, { x: MARGIN + 16, y, size: 11, font: fonts.bold, color: CHARCOAL })
    y -= 14
    const detail = [item.dosage, item.frequency, item.duration].filter(Boolean).join('   ·   ')
    if (detail) {
      page.drawText(detail, { x: MARGIN + 32, y, size: 9, font: fonts.regular, color: GREY })
      y -= 12
    }
    if (item.instructions) {
      page.drawText(item.instructions, { x: MARGIN + 32, y, size: 8.5, font: fonts.italic, color: GREY })
      y -= 12
    }
    y -= 6
  })

  if (presc.advice) {
    y -= 6
    page.drawText('Advice:', { x: MARGIN, y, size: 9, font: fonts.bold, color: TEAL })
    y -= 13
    page.drawText(presc.advice.slice(0, 110), { x: MARGIN, y, size: 9, font: fonts.regular, color: CHARCOAL })
    y -= 12
  }
  if (presc.follow_up_date) {
    page.drawText(`Follow-up: ${presc.follow_up_date}`, { x: MARGIN, y, size: 9, font: fonts.bold, color: CHARCOAL })
    y -= 12
  }

  // signature line
  page.drawLine({ start: { x: PAGE_W - MARGIN - 160, y: 130 }, end: { x: PAGE_W - MARGIN, y: 130 }, thickness: 0.75, color: GREY })
  page.drawText("Doctor's Signature", { x: PAGE_W - MARGIN - 140, y: 118, size: 8.5, font: fonts.regular, color: GREY })

  drawFooter(page, fonts, clinic)

  const bytes = await pdfDoc.save()
  const dir = exportsDir('prescriptions')
  const filePath = path.join(dir, `${presc.prescription_no}.pdf`)
  fs.writeFileSync(filePath, bytes)
  return filePath
}

module.exports = { generateInvoicePdf, generatePrescriptionPdf, exportsDir }
